In [62]:
#importing libariries
import tweepy
import csv
import json
import pandas as pd
import os
import requests
import re
from nltk.tokenize import word_tokenize
import numpy as np

In [63]:
#load the credentials
with open('twitter_credentials.json', 'r') as file:
    creds = json.load(file)

In [46]:
auth = tweepy.OAuthHandler(creds['CONSUMER_KEY'], creds['CONSUMER_SECRET'])
auth.set_access_token(creds['ACCESS_TOKEN'], creds['ACCESS_SECRET'])
api = tweepy.API(auth,wait_on_rate_limit=True,wait_on_rate_limit_notify=True)

In [1]:
#Funtion for getting tweets
def get_tweets(search_query, num_tweets):
    # Collect tweets using the Cursor object
    # Each item in the iterator has various attributes that you can access to get information about each tweet
    tweet_list = [tweets for tweets in tweepy.Cursor(api.search,
                                    q=search_query,
                                    lang="en",
                                    tweet_mode='extended').items(num_tweets)]
    # Begin scraping the tweets individually:
    for tweet in tweet_list:
        tweet_id = tweet.id # get Tweet ID result
        created_at = tweet.created_at # get time tweet was created
        text = tweet.full_text # retrieve full tweet text
        location = tweet.user.location # retrieve user location
        retweet = tweet.retweet_count # retrieve number of retweets
        favorite = tweet.favorite_count # retrieve number of likes
        source = tweet.source
        
        with open(r'Justiceleague_2.csv','a', newline='', encoding='utf-8') as csvFile:
            csv_writer = csv.writer(csvFile, delimiter=',') # create an instance of csv object
            csv_writer.writerow([tweet_id, created_at, text, location, retweet, favorite, source]) # write each row

In [5]:
# Specifying exact phrase to search for. This is not case senstitive
search_words = "Justice League OR #SnyderCut OR #SnyderCutJusticeLeague OR #RestoreTheSnyderVerse OR #restorethesnyderverse"
# Exclude Links, retweets, replies
search_query = search_words + " -filter:retweets AND -filter:replies"
#with open('tweets_bridgerton.csv', encoding='utf-8') as data:
    #latest_tweet = int(list(csv.reader(data))[-1][0]) # Return the most recent tweet ID
get_tweets(search_query,50000) # Call your function and pass in your search query and number of tweets you want to get

Rate limit reached. Sleeping for: 804
Rate limit reached. Sleeping for: 808
Rate limit reached. Sleeping for: 815
Rate limit reached. Sleeping for: 814
Rate limit reached. Sleeping for: 817
Rate limit reached. Sleeping for: 814
Rate limit reached. Sleeping for: 817
Rate limit reached. Sleeping for: 816
Rate limit reached. Sleeping for: 817
Rate limit reached. Sleeping for: 817
Rate limit reached. Sleeping for: 813
Rate limit reached. Sleeping for: 819
Rate limit reached. Sleeping for: 819
Rate limit reached. Sleeping for: 818
Rate limit reached. Sleeping for: 817

In [4]:
# THIS FUNCTION IS USED TO MINE TWEETS THAT ARE OLDER THAN THE TWEETS YOU HAVE.
def get_tweets2(search_query, num_tweets, max_id_num):
    # Collect tweets using the Cursor object
    # Each item in the iterator has various attributes that you can access to get information about each tweet
    tweet_list = [tweets for tweets in tweepy.Cursor(api.search,
                                    q=search_query,
                                    lang="en",
                                    since_id=max_id_num, # max_id is the oldest tweet id you have
                                    tweet_mode='extended').items(num_tweets)]
    
    # Begin scraping the tweets individually:
    for tweet in tweet_list:
        tweet_id = tweet.id # get Tweet ID result
        created_at = tweet.created_at # get time tweet was created
        text = tweet.full_text # retrieve full tweet text
        location = tweet.user.location # retrieve user location
        retweet = tweet.retweet_count # retrieve number of retweets
        favorite = tweet.favorite_count # retrieve number of likes
        source = tweet.source
        
        with open(r'New_SnyderCut.csv','a', newline='', encoding='utf-8') as csvFile:
            csv_writer = csv.writer(csvFile, delimiter=',') # create an instance of csv object
            csv_writer.writerow([tweet_id, created_at, text, location, retweet, favorite, source]) # write each row

In [5]:
# Specifying exact phrase to search for. This is not case senstitive
search_words = "Justice League OR #SnyderCut OR #SnyderCutJusticeLeague OR #RestoreTheSnyderVerse OR #restorethesnyderverse"
# Exclude Links, retweets, replies
search_query = search_words + " -filter:retweets AND -filter:replies"
#oldest_tweet = int(list(csv.reader(data))[-1][0])
with open('Justiceleague_2.csv', encoding='utf-8') as data:
    oldest_tweet = int(list(csv.reader(data))[-1][0]) # Return the most recent tweet ID
get_tweets2(search_query,100000,oldest_tweet) # Call your function and pass in your search query and number of tweets you want to get

Rate limit reached. Sleeping for: 764
Rate limit reached. Sleeping for: 814
Rate limit reached. Sleeping for: 791
Rate limit reached. Sleeping for: 807
Rate limit reached. Sleeping for: 817
Rate limit reached. Sleeping for: 807
Rate limit reached. Sleeping for: 809
Rate limit reached. Sleeping for: 809
Rate limit reached. Sleeping for: 815
Rate limit reached. Sleeping for: 797
Rate limit reached. Sleeping for: 709

In [101]:
#getting tweet from zack snyder's account
number_of_tweets = 200
tweet_id = []
created_at = []
tweets = []
likes = []
for i in tweepy.Cursor(api.user_timeline, id ='ZackSnyder', tweet_mode = "extended").items(number_of_tweets):
    tweet_id.append(i.id)
    created_at.append(i.created_at)
    tweets.append(i.full_text)
    likes.append(i.favorite_count)

In [102]:
#giving the data frame headers and saving the new dataframe
df = pd.DataFrame({'tweet_id': tweet_id, 'created_at': time, 'tweets': tweets, 'likes': likes})
df.to_csv('Zack_Snyder.csv', index = False)

In [117]:
#getting tweet from SnyderCut's account
number_of_tweets = 200
tweet_id = []
created_at = []
tweets = []
likes = []
for i in tweepy.Cursor(api.user_timeline, id ='snydercut', tweet_mode = "extended").items(number_of_tweets):
    tweet_id.append(i.id)
    created_at.append(i.created_at)
    tweets.append(i.full_text)
    likes.append(i.favorite_count)

In [1]:
#giving the data frame headers and saving the new dataframe
df = pd.DataFrame({'tweet_id': tweet_id, 'created_at': time, 'tweets': tweets, 'likes': likes})
df.to_csv('Zack_Snyder_Cut.csv', index = False)

In [7]:
#getting tweet from RayFisher's account
number_of_tweets = 500
tweet_id = []
created_at = []
tweets = []
likes = []
for i in tweepy.Cursor(api.user_timeline, id ='ray8fisher', tweet_mode = "extended").items(number_of_tweets):
    tweet_id.append(i.id)
    created_at.append(i.created_at)
    tweets.append(i.full_text)
    likes.append(i.favorite_count)

In [9]:
#giving the data frame headers and saving the new dataframe
df = pd.DataFrame({'tweet_id': tweet_id, 'created_at': created_at, 'tweets': tweets, 'likes': likes})
df.to_csv('Ray_Fisher.csv', index = False)

In [47]:
#getting tweet from HBOMax's account
number_of_tweets = 4000
tweet_id = []
created_at = []
tweets = []
likes = []
for i in tweepy.Cursor(api.user_timeline, id ='hbomax', tweet_mode = "extended").items(number_of_tweets):
    tweet_id.append(i.id)
    created_at.append(i.created_at)
    tweets.append(i.full_text)
    likes.append(i.favorite_count)

In [48]:
df = pd.DataFrame({'tweet_id': tweet_id, 'created_at': created_at, 'tweets': tweets, 'likes': likes})
df.to_csv('HBOmax.csv', index = False)

In [110]:
#giving the first file a header
name = ['tweet_id', 'created_at', 'tweet', 'location', 'retweet', 'likes', 'source']
df = pd.read_csv('Justiceleague_2.csv', header = None, skiprows = 1, names = name)
df.tail()

In [72]:
#saving to csv
df.to_csv('Justice_league_1.csv',index=False)

In [75]:
#displaying the new data
df2 = pd.read_csv('Justice_league_1.csv')
df2.head()

,tweet_id,created_at,tweet,location,retweet,likes,source
0,1376992630794547203,2021-03-30 20:20:01,Exclusive: Connie Nielsen Talks Zack Snyder’s ...,"Albuquerque, NM",0,0,Buffer
1,1376992549034979329,2021-03-30 20:19:41,Honest Trailers | Zack Snyder's Justice League...,NaN,0,0,Twitter Web App
2,1376992406441189380,2021-03-30 20:19:07,Watching that new Zack Snyder's Justice League...,Glasgow,0,0,Twitter for iPhone
3,1376992216808370181,2021-03-30 20:18:22,"Justice League are a man down because, Batman....",36°49′E / 1.283°S 36.817°E,0,0,Twitter for Android
4,1376992071375056896,2021-03-30 20:17:47,I was on a podcast! 👍🏻 https://t.co/HX3x51Tswv,UK,0,0,Twitter for iPhone

In [8]:
#giving the second file a header
name = ['tweet_id', 'created_at', 'tweet', 'location', 'retweet', 'likes', 'source']
df = pd.read_csv('New_SnyderCut.csv', header = None, skiprows = 1, names = name)
df.tail()

,tweet_id,created_at,tweet,location,retweet,likes,source
30353,1375176473313705989,2021-03-25 20:03:15,Zack Snyder’s Justice league is one of the bes...,"Kaliningrad, Russia",0,0,Twitter for iPhone
30354,1375176445941583874,2021-03-25 20:03:08,JUSTICE LEAGUE Fans Campaigning for WARNER BRO...,Barb deserved better,75,295,TweetDeck
30355,1375176291381432322,2021-03-25 20:02:32,Justice League Flash is lightskin https://t.co...,black lives matta • they/them,2,7,Twitter for iPhone
30356,1375176214902673414,2021-03-25 20:02:13,This will never end. Justice will prevail #Re...,NaN,1,3,Twitter for iPhone
30357,1375176185106337798,2021-03-25 20:02:06,"Okay, but when are we getting the sepia versio...",NaN,0,1,Twitter Web App

In [9]:
#saving to csv
df.to_csv('Justiceleague_2.csv',index=False)

In [10]:
#merging the two csvs
master_df = pd.DataFrame()

for file in os.listdir(os.getcwd()):
    if file.endswith('.csv'):
        master_df = master_df.append(pd.read_csv(file))
        
master_df.to_csv('Justice_League.csv', index = False)

In [4]:
tweet_df = pd.read_csv('Justice_League.csv')
tweet_df.tail()

,tweet_id,created_at,tweet,location,retweet,likes,source
110389,1375176473313705989,2021-03-25 20:03:15,Zack Snyder’s Justice league is one of the bes...,"Kaliningrad, Russia",0,0,Twitter for iPhone
110390,1375176445941583874,2021-03-25 20:03:08,JUSTICE LEAGUE Fans Campaigning for WARNER BRO...,Barb deserved better,75,295,TweetDeck
110391,1375176291381432322,2021-03-25 20:02:32,Justice League Flash is lightskin https://t.co...,black lives matta • they/them,2,7,Twitter for iPhone
110392,1375176214902673414,2021-03-25 20:02:13,This will never end. Justice will prevail #Re...,NaN,1,3,Twitter for iPhone
110393,1375176185106337798,2021-03-25 20:02:06,"Okay, but when are we getting the sepia versio...",NaN,0,1,Twitter Web App

# CLEANING THE DATA

In [5]:
tweet_df.shape #Get number of rows and columns

(110394, 7)

In [6]:
tweet_df.duplicated(subset='tweet_id').sum() # Check for duplicate values

59713

In [7]:
tweet_df=tweet_df.drop_duplicates(subset=['tweet_id']) # drop duplicate values

In [8]:
tweet_df.shape # Check the shape after dropping duplicates

(50681, 7)

In [9]:
tweet_df.isna().any() # Check for "NaN" values

tweet_id      False
created_at    False
tweet         False
location       True
retweet       False
likes         False
source         True
dtype: bool

In [10]:
tweet_df['location']=tweet_df['location'].fillna('No location') # Replace "NaN" values with "No Location"

In [11]:
tweet_df.head()

,tweet_id,created_at,tweet,location,retweet,likes,source
0,1376992630794547203,2021-03-30 20:20:01,Exclusive: Connie Nielsen Talks Zack Snyder’s ...,"Albuquerque, NM",0,0,Buffer
1,1376992549034979329,2021-03-30 20:19:41,Honest Trailers | Zack Snyder's Justice League...,No location,0,0,Twitter Web App
2,1376992406441189380,2021-03-30 20:19:07,Watching that new Zack Snyder's Justice League...,Glasgow,0,0,Twitter for iPhone
3,1376992216808370181,2021-03-30 20:18:22,"Justice League are a man down because, Batman....",36°49′E / 1.283°S 36.817°E,0,0,Twitter for Android
4,1376992071375056896,2021-03-30 20:17:47,I was on a podcast! 👍🏻 https://t.co/HX3x51Tswv,UK,0,0,Twitter for iPhone

In [12]:
tweet_df['source']=tweet_df['source'].fillna('No source') # Replace "NaN" values with "No source"

In [13]:
tweet_df.tail()

,tweet_id,created_at,tweet,location,retweet,likes,source
108995,1375229897543716864,2021-03-25 23:35:32,"This is canon, this is real, this is justice l...","Cuauhtémoc, Distrito Federal",0,0,Twitter Web App
109043,1375228140126003203,2021-03-25 23:28:33,Why Zack Snyder's Justice League Is Changing M...,"Diksmuide, België",0,0,dlvr.it
109799,1375199195490095105,2021-03-25 21:33:32,Zack Snyder’s Justice League was easily the be...,No location,1,1,Twitter for iPhone
110027,1375190246434951170,2021-03-25 20:57:59,We believe in Justice!!! Restore The Snyder Ve...,No location,0,0,Twitter for iPhone
110256,1375182261096615937,2021-03-25 20:26:15,im sending all my girl best friends to dennis ...,Mexico,0,2,Twitter for iPhone

In [84]:
#functioon for getting latitude and longitude of location provided by twitter user
API_KEY = 'AIzaSyAxRUb-D6DkSPFGWSAWM_qoipZOkt9HZFc'

def getGeoCoord(address):
    if address != 'No location':
        params = {
        'key': API_KEY,
        'address': address.replace(' ', '+')
        }

        base_url = 'https://maps.googleapis.com/maps/api/geocode/json?'
        response = requests.get(base_url, params=params)
        data = response.json()
        if data['status'] == 'OK':
            result = data['results'][0]
            location = result['geometry']['location']
            return location['lat'], location['lng']

In [85]:
tweet_df['Location_data']=tweet_df['location'].apply(getGeoCoord) # Apply getCoordinates Function

In [87]:
tweet_df.head()

,tweet_id,created_at,tweet,location,retweet,likes,source,Hashtags,Movie_Characters,Location_data,latitude,longitude
0,1376992630794547203,2021-03-30 20:20:01,Exclusive: Connie Nielsen Talks Zack Snyder’s ...,"Albuquerque, NM",0,0,Buffer,#tv #video #movies #entertainment,,"(35.0843859, -106.650422)",35.0843859,NaN
1,1376992549034979329,2021-03-30 20:19:41,Honest Trailers | Zack Snyder's Justice League...,No location,0,0,Twitter Web App,,,None,None,NaN
2,1376992406441189380,2021-03-30 20:19:07,Watching that new Zack Snyder's Justice League...,Glasgow,0,0,Twitter for iPhone,,,"(55.864237, -4.251806)",55.864237,NaN
3,1376992216808370181,2021-03-30 20:18:22,"Justice League are a man down because, Batman....",36°49′E / 1.283°S 36.817°E,0,0,Twitter for Android,,batman,None,None,NaN
4,1376992071375056896,2021-03-30 20:17:47,I was on a podcast! 👍🏻 https://t.co/HX3x51Tswv,UK,0,0,Twitter for iPhone,,,"(55.378051, -3.435973)",55.378051,NaN

In [93]:
#spliting the latitude and longitutide into different columns
tweet_df[['latitude','longitude']] = pd.DataFrame(tweet_df['Location_data'].tolist(),index=tweet_df.index)

In [94]:
tweet_df.head()

,tweet_id,created_at,tweet,location,retweet,likes,source,Hashtags,Movie_Characters,Location_data,latitude,longitude
0,1376992630794547203,2021-03-30 20:20:01,Exclusive: Connie Nielsen Talks Zack Snyder’s ...,"Albuquerque, NM",0,0,Buffer,#tv #video #movies #entertainment,,"(35.0843859, -106.650422)",35.084386,-106.650422
1,1376992549034979329,2021-03-30 20:19:41,Honest Trailers | Zack Snyder's Justice League...,No location,0,0,Twitter Web App,,,None,NaN,NaN
2,1376992406441189380,2021-03-30 20:19:07,Watching that new Zack Snyder's Justice League...,Glasgow,0,0,Twitter for iPhone,,,"(55.864237, -4.251806)",55.864237,-4.251806
3,1376992216808370181,2021-03-30 20:18:22,"Justice League are a man down because, Batman....",36°49′E / 1.283°S 36.817°E,0,0,Twitter for Android,,batman,None,NaN,NaN
4,1376992071375056896,2021-03-30 20:17:47,I was on a podcast! 👍🏻 https://t.co/HX3x51Tswv,UK,0,0,Twitter for iPhone,,,"(55.378051, -3.435973)",55.378051,-3.435973

In [17]:
#function to remove and get hastags
def getHashtags(tweet):
    tweet = tweet.lower()  #has to be in place
    tweet = re.findall(r'\#\w+',tweet) # Remove hastags with REGEX
    return " ".join(tweet)

In [49]:
tweet_df['Hashtags'] = tweet_df['tweet'].apply(getHashtags)
tweet_df.head()

,tweet_id,created_at,tweet,location,retweet,likes,source,Hashtags,Movie_Characters
0,1376992630794547203,2021-03-30 20:20:01,Exclusive: Connie Nielsen Talks Zack Snyder’s ...,"Albuquerque, NM",0,0,Buffer,#tv #video #movies #entertainment,
1,1376992549034979329,2021-03-30 20:19:41,Honest Trailers | Zack Snyder's Justice League...,No location,0,0,Twitter Web App,,
2,1376992406441189380,2021-03-30 20:19:07,Watching that new Zack Snyder's Justice League...,Glasgow,0,0,Twitter for iPhone,,
3,1376992216808370181,2021-03-30 20:18:22,"Justice League are a man down because, Batman....",36°49′E / 1.283°S 36.817°E,0,0,Twitter for Android,,batman
4,1376992071375056896,2021-03-30 20:17:47,I was on a podcast! 👍🏻 https://t.co/HX3x51Tswv,UK,0,0,Twitter for iPhone,,

In [25]:
hashtags_list = tweet_df['Hashtags'].tolist()

#iterate over all hashtags so they can be split where there is more than one hashtag per row
hashtags = []
for item in hashtags_list:
    item = item.split()
    for i in item:
        hashtags.append(i)

# Use the Built-in Python Collections module to determine Unique count of all hashtags used
from collections import Counter
counts = Counter(hashtags)
hashtags_df = pd.DataFrame.from_dict(counts, orient='index').reset_index()
hashtags_df.columns = ['Hashtags', 'Count']
hashtags_df.sort_values(by='Count', ascending=False, inplace=True)
print (f'Total Number of Unique Hashtags is: {hashtags_df.shape[0]}.')

Total Number of Unique Hashtags is: 3683.

In [26]:
hashtags_df["Percentage"] = 100*(hashtags_df["Count"]/hashtags_df['Count'].sum())
hashtags_df = hashtags_df.head(10)

In [27]:
hashtags_df

                      Hashtags  Count  Percentage
5       #restorethesnyderverse   6374   21.411535
11                  #snydercut   2656    8.922033
14   #zacksnydersjusticeleague   2220    7.457422
47              #justiceleague   1414    4.749908
4      #restorethesnyderverese    462    1.551950
173             #justiceisgray    458    1.538513
27     #justiceleaguesnydercut    419    1.407504
57                     #batman    408    1.370553
84                   #superman    389    1.306728
41      #restorethesynderverse    367    1.232826

In [38]:
#list of important justice league characters
justiceleague_characters = ['batman', 'superman', 'wonderwoman', 'flash', 'cyborg', 'aquaman', 'darkside', 'steppenwolf'
                        'joker', 'deathstroke', 'lex luthor', 'amazons', 'barry allen' ]

In [39]:
# Function to extract Bridgerton Characters from each Tweet
def getMovieCharacters(tweet):
    tweet = tweet.lower() # Reduce tweet to lower case
    tweet_tokens = word_tokenize(tweet) # split each word in the tweet for parsing
    movie_characters = [char for char in tweet_tokens if char in justiceleague_characters] # extract movie characters
    return " ".join(movie_characters)

In [40]:
# Extract Movie characters to a new column
tweet_df['Movie_Characters'] = tweet_df['tweet'].apply(getMovieCharacters)
tweet_df.tail()

,tweet_id,created_at,tweet,location,retweet,likes,source,Hashtags,Movie_Characters
108995,1375229897543716864,2021-03-25 23:35:32,"This is canon, this is real, this is justice l...","Cuauhtémoc, Distrito Federal",0,0,Twitter Web App,#restorethesnyderverse,
109043,1375228140126003203,2021-03-25 23:28:33,Why Zack Snyder's Justice League Is Changing M...,"Diksmuide, België",0,0,dlvr.it,,flash
109799,1375199195490095105,2021-03-25 21:33:32,Zack Snyder’s Justice League was easily the be...,No location,1,1,Twitter for iPhone,#restorethesnyderverse,
110027,1375190246434951170,2021-03-25 20:57:59,We believe in Justice!!! Restore The Snyder Ve...,No location,0,0,Twitter for iPhone,#restorethesnyderverse #releasetheayercut #bat...,
110256,1375182261096615937,2021-03-25 20:26:15,im sending all my girl best friends to dennis ...,Mexico,0,2,Twitter for iPhone,,

In [1]:
characters_list = tweet_df['Movie_Characters'].tolist()

#iterate over all hashtags so they can be split where there is more than one hashtag per row
characters = []
for item in characters_list:
    item = item.split()
    for i in item:
        characters.append(i)

# Use the Built-in Python Collections module to determine Unique count of all hashtags used
from collections import Counter
counts = Counter(characters)
characters_df = pd.DataFrame.from_dict(counts, orient='index').reset_index()
characters_df.columns = ['Movie_Characters', 'Count']
characters_df.sort_values(by='Count', ascending=False, inplace=True)
print (f'Total Number of Unique Characters is: {characters_df.shape[0]}.')
characters_df.head(10)

In [2]:
characters_df['Percentage'] = 100*(characters_df['Count'] / characters_df['Count'].sum())
characters_df

In [105]:
#saving to csv
characters_df.to_csv('characters.csv',index=False)

In [96]:
tweet_df.drop(['location','Location_data',], axis = 1, inplace = True)

In [97]:
tweet_df.head()

,tweet_id,created_at,tweet,retweet,likes,source,Hashtags,Movie_Characters,latitude,longitude
0,1376992630794547203,2021-03-30 20:20:01,Exclusive: Connie Nielsen Talks Zack Snyder’s ...,0,0,Buffer,#tv #video #movies #entertainment,,35.084386,-106.650422
1,1376992549034979329,2021-03-30 20:19:41,Honest Trailers | Zack Snyder's Justice League...,0,0,Twitter Web App,,,NaN,NaN
2,1376992406441189380,2021-03-30 20:19:07,Watching that new Zack Snyder's Justice League...,0,0,Twitter for iPhone,,,55.864237,-4.251806
3,1376992216808370181,2021-03-30 20:18:22,"Justice League are a man down because, Batman....",0,0,Twitter for Android,,batman,NaN,NaN
4,1376992071375056896,2021-03-30 20:17:47,I was on a podcast! 👍🏻 https://t.co/HX3x51Tswv,0,0,Twitter for iPhone,,,55.378051,-3.435973

In [98]:
tweet_df.to_csv('Justice_League_final.csv',index=False)